### ISSUE TITLE
custom methods         TypeError: Cannot read property '$observable' of null

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#15]
```
//login.res

import {Resource, ResourceParams, ResourceAction, ResourceResult} from "ng2-resource-rest";
import {Component,Injectable} from '@angular/core';
import { Cookie } from 'ng2-cookies/ng2-cookies';
let csrftoken = Cookie.get('csrftoken');

// Make it Injectable
@Injectable()
// Decorate the your resource class
@ResourceParams({ 
    url: '',
    headers:{
        "X-CSRFToken":csrftoken,
        'Accept': 'application/json',
        'Content-Type': 'application/json'
    },
    // Api path
    path: '/api-auth/login/'
})
export class LoginRes extends Resource {
    login(data:any, callback?:Function): ResourceResult { return null; }
}
```

      ```
this.Res.login({csrfmiddlewaretoken:'kgEviC68d6OAB23v5fZlu0e1GO5oig7c',next:'/',username:'111111',password:'222222'})
                .$observable
                .subscribe(
                    res => console.log(res),
                    err => console.log('Err', err)
                );
```

error info:

```
browser_adapter.ts:78 ORIGINAL EXCEPTION: TypeError: Cannot read property '$observable' of nullBrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:65(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.ts:100NgZone.runGuarded @ ng_zone.ts:216outsideHandler @ dom_events.ts:16ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:69(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.ts:100NgZone.runGuarded @ ng_zone.ts:216outsideHandler @ dom_events.ts:16ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78 TypeError: Cannot read property '$observable' of null
    at LoginComponent.submitData (login.component.js:76)
    at DebugAppView._View_LoginComponent0._handle_click_27_0 (LoginComponent.template.js:646)
    at eval (view.ts:374)
    at eval (dom_renderer.ts:308)
    at eval (dom_events.ts:16)
    at ZoneDelegate.invoke (zone.js:323)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.ts:67)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.runGuarded (zone.js:230)
    at NgZoneImpl.runInnerGuarded (ng_zone_impl.ts:100)BrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:70(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.ts:100NgZone.runGuarded @ ng_zone.ts:216outsideHandler @ dom_events.ts:16ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:74(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.ts:100NgZone.runGuarded @ ng_zone.ts:216outsideHandler @ dom_events.ts:16ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.ts:78 DebugContext {_view: _View_LoginComponent0, _nodeIndex: 27, _tplRow: 21, _tplCol: 76}BrowserDomAdapter.logError @ browser_adapter.ts:78ExceptionHandler.call @ exception_handler.ts:75(anonymous function) @ application_ref.ts:304schedulerFn @ async.ts:131SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:117NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:138NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:90ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.ts:100NgZone.runGuarded @ ng_zone.ts:216outsideHandler @ dom_events.ts:16ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
zone.js:260 Uncaught EXCEPTION: Error in app/app/login.component.html:21:76
ORIGINAL EXCEPTION: TypeError: Cannot read property '$observable' of null
ORIGINAL STACKTRACE:
TypeError: Cannot read property '$observable' of null
    at LoginComponent.submitData (https://127.0.0.1:30004/app/app/login.component.js:76:17)
    at DebugAppView._View_LoginComponent0._handle_click_27_0 (LoginComponent.template.js:646:28)
    at eval (https://127.0.0.1:30004/node_modules/@angular/core/src/linker/view.js:316:24)
    at eval (https://127.0.0.1:30004/node_modules/@angular/platform-browser/src/dom/dom_renderer.js:278:36)
    at eval (https://127.0.0.1:30004/node_modules/@angular/platform-browser/src/dom/events/dom_events.js:20:93)
    at ZoneDelegate.invoke (https://127.0.0.1:30004/node_modules/zone.js/dist/zone.js:323:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (https://127.0.0.1:30004/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
    at ZoneDelegate.invoke (https://127.0.0.1:30004/node_modules/zone.js/dist/zone.js:322:35)
    at Zone.runGuarded (https://127.0.0.1:30004/node_modules/zone.js/dist/zone.js:230:48)
    at NgZoneImpl.runInnerGuarded (https://127.0.0.1:30004/node_modules/@angular/core/src/zone/ng_zone_impl.js:78:78)
ERROR CONTEXT:
[object Object]
```

**Comment by troyanskiy** [comment]
You need to decorate your login method.

**Comment by iloveyo123u1** [comment]
oh。i  am so sorry, thank you
