### ISSUE TITLE
 No provider for UserRes! (UserComponent -> UserRes)

### ISSUE THREAD

**Issue by iloveyo123u1** [troyanskiy/ng2-resource-rest#7]
EXCEPTION: Error: Uncaught (in promise): No provider for UserRes! (UserComponent -> UserRes)

-------------------------------

i got this error
and then

i add **UserRes** to  **providers**

like this:

```
  providers: [
        RESOURCE_PROVIDERS,
        UserRes
    ]
```

----------

then.i  got new error:

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error during instantiation of UserComponent!.
ORIGINAL EXCEPTION: TypeError: Cannot read property 'request' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'request' of undefined
    at UserRes.descriptor.value [as query] (http://127.0.0.1:8888/node_modules/ng2-resource-rest/index.js:166:43)
    at new UserComponent (http://127.0.0.1:8888/app/user/user.component.js:54:46)
    at http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:1418:20
    at Injector._instantiate (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11770:19)
    at Injector._instantiateProvider (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11709:21)
    at Injector._new (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11699:19)
    at InjectorInlineStrategy.instantiateProvider (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11463:28)
    at ElementDirectiveInlineStrategy.init (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:8998:20)
    at new AppElement (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:8688:24)
    at HostViewFactory.viewFactory_HostUserComponent0 [as viewFactory] (viewFactory_UserComponent:73:42)
```

----------
this my code:
```
//User.component.ts
import {Resource, ResourceParams} from "ng2-resource-rest";
import {RESOURCE_PROVIDERS} from "ng2-resource-rest";
import {Component} from 'angular2/core';
import {UserRes} from "./user.res";


@Component({
    selector: 'user',
    templateUrl: 'app/user/user.component.html',
    providers: [
        RESOURCE_PROVIDERS,
        UserRes
    ]

})
export class UserComponent {
     allUsers: any[];
    constructor(private Res:UserRes) {       
        this.allUsers = this.Res.query();
    }    
}
```

```
//user.res.ts
import {Resource, ResourceParams, ResourceAction, ResourceResult} from "ng2-resource-rest";
import {Injectable} from "angular2/core";
// Make it Injectable
@Injectable()
// Decorate the your resource class
@ResourceParams({
    // Url to api
    url: 'http://127.0.0.1:8888',
    // Api path
    path: '/user/{id}'
})
export class UserRes extends Resource {}
```

**Comment by troyanskiy** [comment]
Should be like that
Remove UserRes from `@Component` it should be in RESOURCE_PROVIDERS
```ts
//User.component.ts
import {Resource, ResourceParams} from "ng2-resource-rest";
import {RESOURCE_PROVIDERS} from "ng2-resource-rest";
import {Component} from 'angular2/core';
import {UserRes} from "./user.res";


@Component({
    selector: 'user',
    templateUrl: 'app/user/user.component.html',
    providers: [
        RESOURCE_PROVIDERS
    ]

})
export class UserComponent {
     allUsers: any[];
    constructor(private Res:UserRes) {       
        this.allUsers = this.Res.query();
    }    
}
```

Please add `@ResourceProvide` decorator to add to the RESOURCE_PROVIDERS. I forgot to describe that in the Docs
```ts
//user.res.ts
import {Resource, ResourceParams, ResourceAction, ResourceResult} from "ng2-resource-rest";
import {Injectable} from "angular2/core";
// Make it Injectable
@Injectable()
// Decorate the your resource class
@ResourceProvide()
@ResourceParams({
    // Url to api
    url: 'http://127.0.0.1:8888',
    // Api path
    path: '/user/{id}'
})
export class UserRes extends Resource {}
```

**Comment by troyanskiy** [comment]
Please wait. I will redo it a little bit now.
Do not use `@ResourceProvide()`

**Comment by troyanskiy** [comment]
It should be fine now.
Please remove from `@Component` providers `UserRes`

**Comment by iloveyo123u1** [comment]
hi,dear troyansikiy
i update to v0.2.3
then i  remove from @Component providers UserRes
run my project
i get a error

---------------

```
EXCEPTION: Unexpected directive value '[object Object]' on the View of component 'AppComponent'
angular2.dev.js:23877 EXCEPTION: Unexpected directive value '[object Object]' on the View of component 'AppComponent'BrowserDomAdapter.logError @ angular2.dev.js:23877BrowserDomAdapter.logGroup @ angular2.dev.js:23888ExceptionHandler.call @ angular2.dev.js:1317(anonymous function) @ angular2.dev.js:12901ZoneDelegate.invoke @ angular2-polyfills.js:332NgZoneImpl.inner.inner.fork.onInvoke @ angular2.dev.js:2111ZoneDelegate.invoke @ angular2-polyfills.js:331Zone.run @ angular2-polyfills.js:227(anonymous function) @ angular2-polyfills.js:576ZoneDelegate.invokeTask @ angular2-polyfills.js:365NgZoneImpl.inner.inner.fork.onInvokeTask @ angular2.dev.js:2103ZoneDelegate.invokeTask @ angular2-polyfills.js:364Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434
angular2.dev.js:23887 EXCEPTION: Error: Uncaught (in promise): Unexpected directive value '[object Object]' on the View of component 'AppComponent'
angular2-polyfills.js:469 Unhandled Promise rejection: Unexpected directive value '[object Object]' on the View of component 'AppComponent' ; Zone: angular ; Task: Promise.then ; Value: BaseException {message: "Unexpected directive value '[object Object]' on the View of component 'AppComponent'", stack: "Error: Unexpected directive value '[object Object]…es/angular2/bundles/angular2-polyfills.js:227:44)"}consoleError @ angular2-polyfills.js:469drainMicroTaskQueue @ angular2-polyfills.js:498ZoneTask.invoke @ angular2-polyfills.js:434
angular2-polyfills.js:471 Error: Uncaught (in promise): Unexpected directive value '[object Object]' on the View of component 'AppComponent'(…)consoleError @ angular2-polyfills.js:471drainMicroTaskQueue @ angular2-polyfills.js:498ZoneTask.invoke @ angular2-polyfills.js:434
angular2-polyfills.js:469 Unhandled Promise rejection: Unexpected directive value '[object Object]' on the View of component 'AppComponent' ; Zone: <root> ; Task: Promise.then ; Value: BaseException {message: "Unexpected directive value '[object Object]' on the View of component 'AppComponent'", stack: "Error: Unexpected directive value '[object Object]…es/angular2/bundles/angular2-polyfills.js:227:44)"}consoleError @ angular2-polyfills.js:469drainMicroTaskQueue @ angular2-polyfills.js:498ZoneTask.invoke @ angular2-polyfills.js:434
angular2-polyfills.js:471 Error: Uncaught (in promise): Unexpected directive value '[object Object]' on the View of component 'AppComponent'(…)

```

**Comment by iloveyo123u1** [comment]
in my project
i run command **tsc**
**$ tsc
../node_modules/ng2-resource-rest/index.ts(365,33): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
**

**Comment by troyanskiy** [comment]
Pushed fix of:
```ts
$ tsc
../node_modules/ng2-resource-rest/index.ts(365,33): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

```

**Comment by troyanskiy** [comment]
I think you should use providers only on app bootstrap.

**Comment by iloveyo123u1** [comment]
```

bootstrap(AppComponent,
    [
        ROUTER_PROVIDERS,
        RESOURCE_PROVIDERS
    ]
)
```

**Comment by iloveyo123u1** [comment]
error again:

`EXCEPTION: Unexpected directive value '[object Object]' on the View of component 'AppComponent'`

**Comment by iloveyo123u1** [comment]
i remove from AppComponent    RESOURCE_PROVIDERS
-----------------
then  i got  
EXCEPTION: Error: Uncaught (in promise): No provider for Http! (UserComponent -> UserRes -> Http)

-----------------------
now  i try fix the error

**Comment by iloveyo123u1** [comment]
```

bootstrap(AppComponent,
    [
        ROUTER_PROVIDERS,
        RESOURCE_PROVIDERS,
        HTTP_PROVIDERS,
    ]
)
```

**Comment by iloveyo123u1** [comment]
Seems to be normal.I need to be sure

**Comment by iloveyo123u1** [comment]
yes ,be fine

**Comment by iloveyo123u1** [comment]
in chrome F12, i can see **ng2-resource-rest **send request
chrome console i can see data

but 
  ```
     this.allUsers = this.Res.get();
        console.log(this.allUsers ) // i can see the data
        window.aa=this.allUsers
        alert(this.allUsers.count ) // i get undefined

```

**Comment by iloveyo123u1** [comment]
in chrome console 
i type **aa**,can got data
i type **aa.count**, can got data

**Comment by iloveyo123u1** [comment]
```
>aa
<Object {$resolved: true, $observable: Observable, count: 31, next: "http://django:8000/user/?page=2", previous: null…}
>aa.count
<31
```

**Comment by iloveyo123u1** [comment]
can you help me

thank you
